# Generated by Django 4.2.16 on 2024-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "city_zip_code",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "user_linkedin",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "company_linkedin",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "angel_link",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "birth_year",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "area_zip_code",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "related_code",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True, default="", max_length=2028, null=True
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True, default="", max_length=2028, null=True
                    ),
                ),
                (
                    "job_categories",
                    models.TextField(
                        blank=True, default="", max_length=2048, null=True
                    ),
                ),
                (
                    "job_skills",
                    models.TextField(
                        blank=True, default="", max_length=2048, null=True
                    ),
                ),
                (
                    "job_tagline",
                    models.TextField(
                        blank=True, default="", max_length=2028, null=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Information",
        ),
    ]
