# Generated by Django 4.2.16 on 2024-10-24 07:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_contact_delete_information"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="full_name",
        ),
        migrations.AddField(
            model_name="contact",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
