# Generated by Django 4.2.16 on 2024-10-24 07:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_contact_full_name_contact_temp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="id",
        ),
        migrations.AlterField(
            model_name="contact",
            name="temp_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
