# Generated by Django 4.2.16 on 2024-10-24 07:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_contact_id_alter_contact_temp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="temp_id",
        ),
        migrations.AddField(
            model_name="contact",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
